### PR TITLE
Implemented Bellman-Ford, fixes #142

### LINKED ISSUE #142: Add Bellman-Ford
Add `bellman_ford.jl` to demonstrate the Bellman-Ford algorithm for finding the shortest paths in a weighted graph, an alternative to the already implemented Dijkstra's algorithm which would allow for negative edge weights.

### PR DESCRIPTION
**Pull request by ybrenning**
I added an implementation of [Bellman-Ford](https://en.wikipedia.org/wiki/Bellman%E2%80%93Ford_algorithm) with documentation. 

For ease of understanding, this implementation uses a graph which is declared as a list of edges where each edge is a tuple with the parameters `(source vertex, destination vertex, weight)`.

### CODE REVIEW

**Comment by ybrenning** [comment]
I also changed the name of the Dijkstra implementation as there was a typo, it seems to have thrown off some of the CI though...

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Hey there! Thank you for submitting a PR! 😄 Please add your algorithm file in `src/TheAlgorithms.jl`. You can check other merged PRs such as in PR #103. Let us know if you need any help here or on our [**Discord server**](https://discord.gg/c7MnfGFGa6). 😃

You will also need to add it to the `test` folder, in a file named `graph.jl`


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by ybrenning** [comment]
image
Since BFS and DFS use the queue and stack data structures which need to be imported in Julia with `using DataStructures`, the logs say we need to include this dependency for the package. 

Is there anywhere else I would need to add the dependency? afaik it should be working since I added it to `TheAlgorithms.jl` which also contains other dependencies such as `Random` and `Linear Algebra` which seem to work just fine

**Comment by Panquesito7** [comment]
> image Since BFS and DFS use the queue and stack data structures which need to be imported in Julia with `using DataStructures`, the logs say we need to include this dependency for the package.
> 
> Is there anywhere else I would need to add the dependency? afaik it should be working since I added it to `TheAlgorithms.jl` which also contains other dependencies such as `Random` and `Linear Algebra` which seem to work just fine

I guess it should be added to `Project.toml`. `Random` and `Linear Algebra` are there.

**Review by Panquesito7 — APPROVED** [review]
Awesome. Thank you! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Maintainable

**Review by uncomfyhalomacro — APPROVED** [review]

**Pull request merged**
