### PR TITLE
Prime Check and Prime Factors

### PR DESCRIPTION
**Pull request by ashwani-rathee**
- [x] Adds prime check, prime factors

### CODE REVIEW

**Review by arubhardwaj — APPROVED** [review]
awesome!

**Comment by arubhardwaj** [comment]
@ashwani-rathee can you check why they are conflicting and resolve at your end?

**Comment by ashwani-rathee** [comment]
Should be resolved now, it happens sometimes when working on same files like TheAlgorithms.jl and test: math.jl

**Review by arubhardwaj — APPROVED** [review]
thanks for solving. I am totally overwhelmed today so couldn't have a look. Thanks

**Pull request merged**
