### PR TITLE
Add binary search

### PR DESCRIPTION
**Pull request by ReneganRonin**
my solution to exercism.io julia track

### CODE REVIEW

**Review by arubhardwaj — CHANGES_REQUESTED** [review]
Please add the instructions in the file too. If you are fine with it @ReneganRonin, can I add them?

**Comment by ReneganRonin** [comment]
@arubhardwaj the instructions is very long so I did not add it. Instead I just point it to the url of the julia track and the problem (in the comments). If you think it is appropriate to add it, then I could include it I guess.

**Comment by arubhardwaj** [comment]
Yes, they are a bit long, but opening links are boring @ReneganRonin.

**Comment by ReneganRonin** [comment]
Alright done :partying_face:

**Review by arubhardwaj — APPROVED** [review]

**Review by arubhardwaj — CHANGES_REQUESTED** [review]
@ReneganRonin Is it looking better now? Can you confirm I made a small edit

**Comment by ReneganRonin** [comment]
@arubhardwaj that looks better in my opinion. hmm i should have use doc strings lol.

**Review by arubhardwaj — APPROVED** [review]

**Comment by arubhardwaj** [comment]
Thanks for contributing @ReneganRonin

**Pull request merged**
