### PR TITLE
Re implementation bubble sort

### PR DESCRIPTION
**Pull request by mieotoha**
(I'm not so good at English, Sorry)
There is such a paragraph in Julia's official document
https://docs.julialang.org/en/v1/manual/style-guide/#Use-naming-conventions-consistent-with-Julia-base/

There is a more concise syntax for exchanging the values of array [j], and array [j + 1]

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks.

**Comment by uncomfyhalomacro** [comment]
Please do edit the [tests](https://github.com/hattori-emi/Julia/blob/main/test/sorts.jl) since you changed the name of the function to `bubble_sort!`, @hattori-emi , that should fix the errors in CI.

**Comment by Azzaare** [comment]
Thank you @hattori-emi 

Do not worry about your skills in English, as many other users are non-native speakers. (必要であれば、日本語での会話も可能です)

About the naming convention, I agree we should follow the classic Julia convention. `bubble_sort!` is unfortunately not the only one that needs some changes.
For your changes, it is also necessary to change the name of `bubble_sort` in the Package main file `src/TheAlgorithms.jl` and in the related test file `test/sorts.jl`
Do you want to do it? If not, I will do it in a couple of days.

**Comment by hattori-emi** [comment]
Thanks for your reply @uncomfyhalomacro and @Azzaare 

In fact, I accidentally found the algorithms project, but I haven't had much time recently, so I can only simply modify the code
I also have no experience in participating in open source projects, so I'm sorry that I didn't consider many things

I think it's better for your to make the changes. In contrast, it may be more convenient for your

**Comment by uncomfyhalomacro** [comment]
It is fine. i can probably suggest my other co-maintainers to merge this and i will just add some changes so CI will pass and Codecov will not give any more annoying warnings. is it fine @Azzaare and @Panquesito7 ??

**Comment by Azzaare** [comment]
@hattori-emi this is more than fine. There is no need to close the pull-request, we can build upon your changes.
(This is a common way to collaborate on open-source repositories)

We're glad to have people joining and participating, for both big and small changes. 

Once again thank you and do not worry. I think both the Julia community and the TheAlgorithms community are kind and welcoming. Do not hesitate to propose other modifications in the future.

**Review by Panquesito7 — DISMISSED** [review]
👍 if CI tests are passing.

**Comment by hattori-emi** [comment]
Thanks

**Review by uncomfyhalomacro — COMMENTED** [review]
LGTM. The loop seems cleaner than the previous one.

**Comment by uncomfyhalomacro** [comment]
I guess CI says otherwise. Going to check why

**Comment by uncomfyhalomacro** [comment]
Hello @mieotoha . I have fixed your code. Please do check if that is what you want.

As for @Panquesito7 and @Azzaare, (sorry for the ping i know you are busy), can you check if it is fine to merge now? CI is passing

**Comment by mieotoha** [comment]
I'm really sorry to have caused you so much trouble
The code you wrote is really correct @uncomfyhalomacro 
But in fact, you only need to modify the flag (the third line of code) to get the correct results
Thank you for your effort

**Comment by uncomfyhalomacro** [comment]
dont worry about it. i think i know it was wrong but i just read the code once and didnt bother to run it lol

**Review by uncomfyhalomacro — DISMISSED** [review]

**Comment by uncomfyhalomacro** [comment]
codecov is failing hmm but tests are passing. i guess this needs some intervention. hmm

**Review by uncomfyhalomacro — APPROVED** [review]

**Pull request merged**
