### PR TITLE
Add solution to Project Euler Problem 011

### PR DESCRIPTION
**Pull request by PraneethJain**
Added solution to Project Euler's problem 11: Largest Product in a Grid
[projecteuler.net/problem=11](https://projecteuler.net/problem=11)

### CODE REVIEW

**Comment by uncomfyhalomacro** [comment]
ha. i havent checked this repository in a long while. 👀

**Comment by PraneethJain** [comment]
Seems like the runs fail because of double imports from the same module?

**Comment by uncomfyhalomacro** [comment]
> Seems like the runs fail because of double imports from the same module?

try explicitly calling what module is the function located

**Comment by PraneethJain** [comment]
> > Seems like the runs fail because of double imports from the same module?
> 
> try explicitly calling what module is the function located

Math.jl was including prime_check.jl and prime_factors.jl twice, fixed it now.

**Comment by PraneethJain** [comment]
Seems like there's other duplicate imports too. Should I create a separate PR just for removing all of them?

**Review by uncomfyhalomacro — APPROVED** [review]
LGTM! 🚀

**Comment by uncomfyhalomacro** [comment]
LGTM! 🚀

**Pull request merged**
