### PR TITLE
Adding Machine Learning Algorithms

### PR DESCRIPTION
**Pull request by Navaneeth-Sharma**
Hi,

I added machine_learning directory, as it was not present. 

Notes that you care about
- [x] Added machine learning directory
- [x] Added linear_regression algorithm

Thank you

### CODE REVIEW

**Comment by Navaneeth-Sharma** [comment]
Hello, Thanks for reviewing. 
Sorry, but I am not able to get the suggestion you made. Is it the "full report at Codecov" you suggested. 
Thank you

**Review by uncomfyhalomacro — APPROVED** [review]

**Comment by uncomfyhalomacro** [comment]
> Hello, Thanks for reviewing. Sorry, but I am not able to get the suggestion you made. Is it the "full report at Codecov" you suggested. Thank you

I did it for you since it is just a minor change in documentation. No need to add tests too since these are ml algorithms. it should be good then

**Comment by uncomfyhalomacro** [comment]
@Navaneeth-Sharma Thanks for the contribution! :D

**Comment by Navaneeth-Sharma** [comment]
Thank you @uncomfyhalomacro for merging and for the support. 
I will try to contribute more to this repository.  :)

**Pull request merged**
