### PR TITLE
sorts and little things

### PR DESCRIPTION
**Pull request by Rratic**

### CODE REVIEW

**Comment by Rratic** [comment]
oh no I used `master` branch again

**Comment by Azzaare** [comment]
> oh no I used `master` branch again

I will solve it, but please `git pull` your branch before making other changes :)

**Comment by Rratic** [comment]
ok

**Comment by Azzaare** [comment]
@Rratic , I have left a PR to update things on your fork. If you merge it, it will update things here!

**Comment by Rratic** [comment]
merged

**Comment by Rratic** [comment]
@Azzaare four days...

**Review by Azzaare — APPROVED** [review]

**Comment by Azzaare** [comment]
@Rratic it happens that you did not actually merge my PR that solves the conflicts here. The PR is still open in your repository. You have updated your code in between which broke my fix. So I had to do it again.

So now, let me handle one thing: BE POLITE, specially when you break the fix of someone ... I happen to have a very busy life at the moment, and this happens to many people, so 4 days is not a long wait. If you are in a hurry, you can ask politely. For instance:
Thank you for your work on this PR @Rratic ! I have updated the PR on your repository, and I will be glad if you can merge it before making other changes.

**Comment by Panquesito7** [comment]
@Azzaare, would that commit fix the merge conflicts? Thanks. 🙂

**Pull request merged**
