### PR TITLE
Least common multiple

### PR DESCRIPTION
**Pull request by Laptop-Salad**
Hi,

I implemented a least common multiple algorithm.

### CODE REVIEW

**Comment by uncomfyhalomacro** [comment]
@Laptop-Salad failed tests. I think you forgot to add `include("pathtoleast_common_multiple.jl")` in `src/TheAlgorithms.jl`

**Comment by uncomfyhalomacro** [comment]
Please see [CONTRIBUTING.md][contrib] for more info.

[contrib]: https://github.com/TheAlgorithms/Julia/blob/main/CONTRIBUTING.md

**Comment by Laptop-Salad** [comment]
> @Laptop-Salad failed tests. I think you forgot to add `include("pathtoleast_common_multiple.jl")` in `src/TheAlgorithms.jl`

Ah okay. I think I have fixed that.

**Review by uncomfyhalomacro — APPROVED** [review]
Good! Thanks for the contribution 🍵

**Pull request merged**
