### PR TITLE
WIP: Activation functions

### PR DESCRIPTION
**Pull request by ashwani-rathee**
- [x] Supposed to cover activation functions

### CODE REVIEW

**Comment by Azzaare** [comment]
Converted to draft to reflect the WIP status ;)

**Comment by Azzaare** [comment]
@ashwani-rathee should this PR considered ready, dead, or keep it as a draft for more time?

**Comment by ashwani-rathee** [comment]
@Azzaare haven't been able to complete this yet, I'll get it ready

**Comment by Azzaare** [comment]
No rush! I was just wondering if I should keep it open or not.

Take your time ;)

**Comment by uncomfyhalomacro** [comment]
@ashwani-rathee sorry for the :ping_pong: . Any news on this PR?

**Comment by Azzaare** [comment]
Same as for #53 , this is a bit old, so we can close it (temporary). The branch is external anyway, so the work would not be deleted.
We can resurrect the PR if needed.

@uncomfyhalomacro @Panquesito7 do you agree?

**Pull request closed without merging**
