### PR TITLE
[WIP] Update contributing

### PR DESCRIPTION
**Pull request by ReneganRonin**
I think we should discuss the contributing.md so people will follow the correct process and so not to create a mess in the repo. Hello @Azzaare @arubhardwaj @Panquesito7. we should discuss this on discord lol.

### CODE REVIEW

**Comment by Azzaare** [comment]
@ReneganRonin it would be nice to not force push if possible ><

**Comment by ReneganRonin** [comment]
> @ReneganRonin it would be nice to not force push if possible ><

Oh my bad. I just like it since i prefer my commit history is consistent with what i am doing. i will adjust and change my ways ><

**Comment by Azzaare** [comment]
> > @ReneganRonin it would be nice to not force push if possible ><
> 
> Oh my bad. I just like it since i prefer my commit history is consistent with what i am doing. i will adjust and change my ways ><

It is not problematic if it is on a branch that is not an active PR, but in that case you actually erased my work.
As I still had it locally it was okay, but force push should never occur (I still do it so it is a bit of do what I say not what I do ...) on a shared repo.

It is not too hard to `git pull` first to merge incoming changes. It is annoying to get the habits, but it helps a ton.

**Comment by ReneganRonin** [comment]
okay sorry. i wont do that again.

**Comment by Azzaare** [comment]
You erased my work again. Stop force push.

In case you want to work independently, please make a new branch.

I won't correct thing for tonight, I will take some time tomorrow.

**Pull request closed without merging**
