### PR TITLE
Hamming distance 

### PR DESCRIPTION
**Pull request by saybarsnazlica**
I implemented the algorithm to find the hamming distance between two strings. I added tests to the `test/strings.jl`.

### CODE REVIEW

**Comment by saybarsnazlica** [comment]
I had some trouble running the tests at first. I found by checking the official documentation that it's as easy as `cd <project_dir>`, `activate . ` inside the REPL and `test`. I guess adding this to the README would be very helpful for newcomers. Should I open an issue about this?

**Comment by uncomfyhalomacro** [comment]
> I had some trouble running the tests at first. I found by checking the official documentation that it's as easy as `cd <project_dir>`, `activate . ` inside the REPL and `test`. I guess adding this to the README would be very helpful for newcomers. Should I open an issue about this? 

sure! sorry for replying so late. i got busy with personal matters. I will take a look at this PR tomorrow as well. thabks for contributing to this repo :)

**Review by Panquesito7 — APPROVED** [review]

**Review by uncomfyhalomacro — APPROVED** [review]

**Comment by uncomfyhalomacro** [comment]
Thanks for the wonderful contribution @saybarsnazlica! I just got out of holiday and vacation.

**Comment by saybarsnazlica** [comment]
Thanks. Hoping to contribute more in the future!

**Pull request merged**
