### PR TITLE
Document variance

### PR DESCRIPTION
**Pull request by ReneganRonin**
To resolve issue #37

### CODE REVIEW

**Comment by ReneganRonin** [comment]
lol i messed the commits

**Comment by ReneganRonin** [comment]
@arubhardwaj can u see if i fixed the variance function correctly?

**Comment by ReneganRonin** [comment]
i guess i should turn this into a fraction since comparing floating point does not make sense to me 🤔

**Review by Azzaare — APPROVED** [review]
Thanks!

EDIT: I have no idea why the CI tests were back to an old config ... rerunning them seems to fix things

Also I think that the variance formula is fixed

**Pull request merged**
