### PR TITLE
Project Euler 17-20

### PR DESCRIPTION
**Pull request by PraneethJain**
Added solutions to Project Euler 17,18,19 and 20.

### CODE REVIEW

**Comment by uncomfyhalomacro** [comment]
well that's a lot, do you want me to merge this now?

**Comment by PraneethJain** [comment]
Yeah, sure.

**Comment by PraneethJain** [comment]
Would it be preferred to open separate PRs for each problem or bunching them together is fine?

**Comment by uncomfyhalomacro** [comment]
> Would it be preferred to open separate PRs for each problem or bunching them together is fine?

It should be fine :D theyre all separate commits anyway. i will just do a merge commit with no squash

**Review by uncomfyhalomacro — APPROVED** [review]

**Pull request merged**
