### PR TITLE
added rotation matrix

### PR DESCRIPTION
**Pull request by Ved-Mahajan**

### CODE REVIEW

**Comment by Rratic** [comment]
Perhaps you _have to_ `export` it.

**Comment by Ved-Mahajan** [comment]
> Perhaps you _have to_ `export` it.

yeah..

sorry that totally slipped out of my mind :sweat:

**Comment by Ved-Mahajan** [comment]
hmm I will look at the tests once more..it was working on my pc :thinking:

**Comment by arubhardwaj** [comment]
@Ved-Mahajan ping me once you feel it is ready for review

**Comment by Ved-Mahajan** [comment]
@arubhardwaj I guess this PR is now ready for review.

**Review by arubhardwaj — APPROVED** [review]

**Pull request merged**
