### PR TITLE
Create OLS.jl

### PR DESCRIPTION
**Pull request by arubhardwaj**
I added code for calculating coefficients in regression using the ordinary east squares. I added both the manual code for calculating the coefficients and solving using the [ GLM.jl ](https://juliastats.org/GLM.jl/v0.11/) package.

### CODE REVIEW

**Comment by maltejur** [comment]
I would call the file `ordinary_least_squares.jl` to make things clearer.

**Review by Panquesito7 — APPROVED** [review]

**Review by maltejur — CHANGES_REQUESTED** [review]
Could you add tests like [here](https://github.com/TheAlgorithms/Julia/blob/7d59bb24b489701b8d517172302a1e4adf6d94f1/math/line_length.jl)?

**Comment by arubhardwaj** [comment]
@maltejur Thanks for the suggestions for the name change of the file. I agree with that. However, I am confused why we need to add tests here? It is just a script, not some package? Is it mandatory to do that? I did not find it in any other repo of The Algorithms so ignored it.

**Comment by maltejur** [comment]
The python and c-sharp repos have tests and the other new pr also had them, so I thought it was a good idea. It is a good and uniform way to show the person reading the code what the expected results are. But we could say adding tests is optional. What do you think?

**Comment by arubhardwaj** [comment]
In my opinion, if we run the script step by step it will clearly show the results. Is there only one purpose of these tests - to let the person running know the answers?

**Comment by maltejur** [comment]
> Is there only one purpose of these tests - to let the person running know the answers?

For more complex algorithms/data structures that span over multiple files it also ensures that a little change doesn't break a small edge case. You could also write the whole algorithm test driven (you start with the tests and then implement until every test passes).

But I agree that it doesn't really make sense for the `sir`, so I'd say we recommend in the `contributing.md` to add tests, but don't require it. Does that sound good, or is that still too much?

**Comment by arubhardwaj** [comment]
I think it's fine. If we find some algorithms which are in multiple files
and are complex, tests may be required. But for small code and little
functions it'll be unnecessary

**Comment by maltejur** [comment]
Okay so we'll make it completely optional

Another thing: I do not really know Julia, I am just helping out here, so I have a question about the dependencies you used. Is there any way to save dependencies in a file, so users downloading the repo can just install all dependencies (like nodejs `package.json` or python `requirements.txt`)? Would it make sense to add `import Pkg; Pkg.add("GLM")` to the start of the file?

**Comment by arubhardwaj** [comment]
I think it should be added like this:
``using Pkg``
``Pkg.add("GLM")``

But I think installing packages is the basic thing every julia user would know

**Comment by maltejur** [comment]
What about CI, how can that install all the required dependencies? For example, I tried to add a small workflow [here](https://github.com/TheAlgorithms/Julia/blob/adf34accdb19b1dd99cd161921fd4d26fba070fb/.github/workflows/test.yaml), that tries to run every file and check all the tests on a pull request. Wouldn't that miss some of the dependencies?

**Comment by arubhardwaj** [comment]
I think we should stay away from creating multiple files. Also, I was wondering if it is possible to add all the algorithms people contribute here in one Julia package? That way dependencies will be handled well.

**Review by Panquesito7 — APPROVED** [review]

**Pull request merged**
