### PR TITLE
adding knapsack

### PR DESCRIPTION
**Pull request by Rratic**

### CODE REVIEW

**Comment by Rratic** [comment]
As a `First-time contributors`,can anyone tell me what to do?

**Comment by arubhardwaj** [comment]
Hi @Rratic, thanks for your contribution. I will review it soon and approve or is there is anything needed I will suggest edits. Will do it in a few hours. Thanks!

**Comment by Rratic** [comment]
Thanks!

**Review by arubhardwaj — CHANGES_REQUESTED** [review]
@Rratic thanks for this. Can you please add a test file in the test folder, too? I am asking for this because this code shows an algorithm but doesn't show the output of these functions.

**Comment by Rratic** [comment]
Sorry,I didn't notice it.
Now I force-pushed this.

**Review by arubhardwaj — APPROVED** [review]
thanks for edits

**Pull request merged**
