### PR TITLE
Adding Caesar Cipher Program

### PR DESCRIPTION
**Pull request by Ihjass**

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Hey there! Thank you for submitting a PR! 😄 Please add your algorithm file in `src/TheAlgorithms.jl`. You can check other merged PRs such as in PR #103. Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6). 😃

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Review by uncomfyhalomacro — CHANGES_REQUESTED** [review]
@Ihjass Hello. I reviewed your code. I have requested some minor changes :smile:

**Review by Panquesito7 — DISMISSED** [review]
There are also [**merge conflicts**](https://github.com/TheAlgorithms/Julia/pull/105/conflicts). Please fix the conflicts.
Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6). 😃

**Review by uncomfyhalomacro — APPROVED** [review]

**Comment by uncomfyhalomacro** [comment]
@Panquesito7 Hello. Can you please merge this PR to main since the CI is blocking it? I do not have access to main branch so I cannot do the manual merging. Thanks!

**Review by Panquesito7 — APPROVED** [review]

**Pull request merged**
