### PR TITLE
feat: add directory and filename formatter workflow

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Add directory and filename formatter workflow.
- Various filenames/directories were updated to match snake_case.

### CODE REVIEW

**Review by uncomfyhalomacro — DISMISSED** [review]
Let's just merge this for now and find out later why it messes up in ubuntu-latest

**Comment by uncomfyhalomacro** [comment]
nvm. found out the failure.

**Comment by uncomfyhalomacro** [comment]
@Panquesito7 should be good now. :D

**Comment by uncomfyhalomacro** [comment]
@Panquesito7 you can merge this now since I can't review my own changes. Hopefully this will work.

**Comment by Panquesito7** [comment]
> @Panquesito7 you can merge this now since I can't review my own changes. Hopefully this will work.

Thanks! :)

**Pull request merged**
