### PR TITLE
added project-rosalind folder and some starter

### PR DESCRIPTION
**Pull request by Ved-Mahajan**
This is to start the folder for the solutions to project rosalind in julia

I have added two codes as a starter!

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
@arubhardwaj, would you like to review this PR? Thanks. 🙂

**Comment by arubhardwaj** [comment]
Thanks for mentioning me @Panquesito7. I will review it in the morning.

**Comment by arubhardwaj** [comment]
I can confirm that the functions are running fine. @Ved-Mahajan is a pro!

**Review by arubhardwaj — APPROVED** [review]
This looks good to me!

**Pull request merged**
